$axure.loadCurrentPage({
  "url":"login.html",
  "generationDate":new Date(1397964633828.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"551d828e795c4133b8d55a65006e1767",
    "type":"Axure:Page",
    "name":"login",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFCC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5471484a87d942eaa878abc8ea5a9947",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":200,
              "y":50},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c65010a011224deb8705283aa9b1b492",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":50},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u0.png"}},
{
          "id":"ebec716dc7cf4a0fa841d27dce1ce311",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":50},
            "size":{
              "width":360,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8efb33e49b1a46868c79c0efc5fa9470",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":50},
                "size":{
                  "width":360,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"c3e7150362d44cde8025d6365850ffbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":230},
            "size":{
              "width":300,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73418b64d6454101805a6c84718d6a4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":230},
                "size":{
                  "width":300,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u4.png"}},
{
          "id":"360c0212d17c449fbda523fd6cc5c359",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei'",
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":245,
              "y":230},
            "size":{
              "width":152,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d316667ac7f46a099e70a68d055744b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":245,
                  "y":230},
                "size":{
                  "width":152,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba1376ee4605411f96def9f65e3dcc8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":300},
            "size":{
              "width":300,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7de6e05f1d24a959c70541108e24439",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":300},
                "size":{
                  "width":300,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u4.png"}},
{
          "id":"ce2deff3e44d4bb798cdac2708ab05ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei'",
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":245,
              "y":300},
            "size":{
              "width":152,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abefbcb922ec4e879d556eb5f5c6731a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":245,
                  "y":300},
                "size":{
                  "width":152,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a33957ae347a4ce296a9389a18af8ac1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":225,
              "y":352},
            "size":{
              "width":32,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5566bf85b4942ab877c5d85d877d27b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":225,
                  "y":352},
                "size":{
                  "width":32,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u12.png"}},
{
          "id":"7560722fa2b84427950567e8c1143c83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei'",
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":255,
              "y":352},
            "size":{
              "width":80,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f6c667dc76448619c1a54e86198fdd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":255,
                  "y":352},
                "size":{
                  "width":80,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d35729f5309943dcad95e94f245d7c26",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF3BCCB5},
            "location":{
              "x":290,
              "y":420},
            "size":{
              "width":179,
              "height":45},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3BCCB5},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb276e8c6ee147699e5311581bf53482",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3BCCB5},
                "location":{
                  "x":290,
                  "y":420},
                "size":{
                  "width":179,
                  "height":45},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3BCCB5},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u16.png"}},
{
          "id":"e292ba4144fa46dda705571ce2cd5ce2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Apple Chancery Chancery', 'Apple Chancery'",
            "fontSize":"28px",
            "fontStyle":"italic",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3BCCB5,
              "opacity":1},
            "location":{
              "x":245,
              "y":144},
            "size":{
              "width":275,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ce2358980a84cfab790b0f03e2e7008",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Apple Chancery Chancery', 'Apple Chancery'",
                "fontSize":"28px",
                "fontStyle":"italic",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3BCCB5,
                  "opacity":1},
                "location":{
                  "x":245,
                  "y":144},
                "size":{
                  "width":275,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6041700e85641ae8cc44b97363ae1f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":630,
              "y":50},
            "size":{
              "width":360,
              "height":640},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3552f3bec308446081178325b158d073",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":630,
                  "y":50},
                "size":{
                  "width":360,
                  "height":640},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u0.png"}},
{
          "id":"c188bb16d1494f2ab6ab3c544f23ca62",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":50},
            "size":{
              "width":360,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62be64d1fe67427b9033e5b9472d0812",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":50},
                "size":{
                  "width":360,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"22acb0b90709496ebe8433b14f2ff736",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":660,
              "y":230},
            "size":{
              "width":300,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b4dbdd5dbfd436daa4e4bad6834fffc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":660,
                  "y":230},
                "size":{
                  "width":300,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u4.png"}},
{
          "id":"dd00ecefe380490f9bc9940596f245e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei'",
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":675,
              "y":230},
            "size":{
              "width":152,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc3c5e2c18264012af2e08bcc37dee26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":675,
                  "y":230},
                "size":{
                  "width":152,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d58c8601298d466a864a5686f2f2d052",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":660,
              "y":300},
            "size":{
              "width":300,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40ec2ed273af4777842b125190efe0c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":660,
                  "y":300},
                "size":{
                  "width":300,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u4.png"}},
{
          "id":"a86645596b1a4319ab99d8dd47630a66",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei'",
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":675,
              "y":300},
            "size":{
              "width":152,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a623fe93cd4d42b59a95c3fb423cbd5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":675,
                  "y":300},
                "size":{
                  "width":152,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd466403053747ef9a846145dc222ca5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":655,
              "y":350},
            "size":{
              "width":32,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d36bd7d585e34daab624e2ffcac3e9aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":655,
                  "y":350},
                "size":{
                  "width":32,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u12.png"}},
{
          "id":"a84ae6a54d3b4061a9406f7e3bc7b49b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei'",
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":685,
              "y":350},
            "size":{
              "width":80,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"827be1bdd7214a7c93e7ffe504ec549e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":685,
                  "y":350},
                "size":{
                  "width":80,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8de0ed2ac8f4bc381dd04d0b5e075f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF3BCCB5},
            "location":{
              "x":720,
              "y":420},
            "size":{
              "width":179,
              "height":45},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3BCCB5},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e91dd5a13ee42898a92cfebace36b3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3BCCB5},
                "location":{
                  "x":720,
                  "y":420},
                "size":{
                  "width":179,
                  "height":45},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3BCCB5},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u16.png"}},
{
          "id":"1af0e05f592b439a9981aace83961ef1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Apple Chancery Chancery', 'Apple Chancery'",
            "fontSize":"28px",
            "fontStyle":"italic",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3BCCB5,
              "opacity":1},
            "location":{
              "x":675,
              "y":144},
            "size":{
              "width":275,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce85fb83d46c49d1b6a0b2d5a998262d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Apple Chancery Chancery', 'Apple Chancery'",
                "fontSize":"28px",
                "fontStyle":"italic",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3BCCB5,
                  "opacity":1},
                "location":{
                  "x":675,
                  "y":144},
                "size":{
                  "width":275,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e54c176ea7294d5594d45445dce8d7b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xBF000000},
            "location":{
              "x":712,
              "y":320},
            "size":{
              "width":201,
              "height":70},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"9"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddd86742aa544ee89fa89d8ee862c402",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xBF000000},
                "location":{
                  "x":712,
                  "y":320},
                "size":{
                  "width":201,
                  "height":70},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"9"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u40.png"}},
{
          "id":"85d0752331414f8799886d216cbae6a2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":330},
            "size":{
              "width":16,
              "height":10},
            "rotation":"45",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/login/u42_line.png"}},
{
          "id":"2c56e16286194aa59419ae901bfe505c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":330},
            "size":{
              "width":16,
              "height":10},
            "rotation":"315",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/login/u42_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "5471484a87d942eaa878abc8ea5a9947":{
      "scriptId":"u0"},
    "c65010a011224deb8705283aa9b1b492":{
      "scriptId":"u1"},
    "ebec716dc7cf4a0fa841d27dce1ce311":{
      "scriptId":"u2"},
    "8efb33e49b1a46868c79c0efc5fa9470":{
      "scriptId":"u3"},
    "c3e7150362d44cde8025d6365850ffbe":{
      "scriptId":"u4"},
    "73418b64d6454101805a6c84718d6a4b":{
      "scriptId":"u5"},
    "360c0212d17c449fbda523fd6cc5c359":{
      "scriptId":"u6"},
    "7d316667ac7f46a099e70a68d055744b":{
      "scriptId":"u7"},
    "ba1376ee4605411f96def9f65e3dcc8d":{
      "scriptId":"u8"},
    "d7de6e05f1d24a959c70541108e24439":{
      "scriptId":"u9"},
    "ce2deff3e44d4bb798cdac2708ab05ec":{
      "scriptId":"u10"},
    "abefbcb922ec4e879d556eb5f5c6731a":{
      "scriptId":"u11"},
    "a33957ae347a4ce296a9389a18af8ac1":{
      "scriptId":"u12"},
    "c5566bf85b4942ab877c5d85d877d27b":{
      "scriptId":"u13"},
    "7560722fa2b84427950567e8c1143c83":{
      "scriptId":"u14"},
    "8f6c667dc76448619c1a54e86198fdd1":{
      "scriptId":"u15"},
    "d35729f5309943dcad95e94f245d7c26":{
      "scriptId":"u16"},
    "bb276e8c6ee147699e5311581bf53482":{
      "scriptId":"u17"},
    "e292ba4144fa46dda705571ce2cd5ce2":{
      "scriptId":"u18"},
    "6ce2358980a84cfab790b0f03e2e7008":{
      "scriptId":"u19"},
    "c6041700e85641ae8cc44b97363ae1f6":{
      "scriptId":"u20"},
    "3552f3bec308446081178325b158d073":{
      "scriptId":"u21"},
    "c188bb16d1494f2ab6ab3c544f23ca62":{
      "scriptId":"u22"},
    "62be64d1fe67427b9033e5b9472d0812":{
      "scriptId":"u23"},
    "22acb0b90709496ebe8433b14f2ff736":{
      "scriptId":"u24"},
    "9b4dbdd5dbfd436daa4e4bad6834fffc":{
      "scriptId":"u25"},
    "dd00ecefe380490f9bc9940596f245e4":{
      "scriptId":"u26"},
    "dc3c5e2c18264012af2e08bcc37dee26":{
      "scriptId":"u27"},
    "d58c8601298d466a864a5686f2f2d052":{
      "scriptId":"u28"},
    "40ec2ed273af4777842b125190efe0c7":{
      "scriptId":"u29"},
    "a86645596b1a4319ab99d8dd47630a66":{
      "scriptId":"u30"},
    "a623fe93cd4d42b59a95c3fb423cbd5b":{
      "scriptId":"u31"},
    "dd466403053747ef9a846145dc222ca5":{
      "scriptId":"u32"},
    "d36bd7d585e34daab624e2ffcac3e9aa":{
      "scriptId":"u33"},
    "a84ae6a54d3b4061a9406f7e3bc7b49b":{
      "scriptId":"u34"},
    "827be1bdd7214a7c93e7ffe504ec549e":{
      "scriptId":"u35"},
    "f8de0ed2ac8f4bc381dd04d0b5e075f7":{
      "scriptId":"u36"},
    "2e91dd5a13ee42898a92cfebace36b3d":{
      "scriptId":"u37"},
    "1af0e05f592b439a9981aace83961ef1":{
      "scriptId":"u38"},
    "ce85fb83d46c49d1b6a0b2d5a998262d":{
      "scriptId":"u39"},
    "e54c176ea7294d5594d45445dce8d7b9":{
      "scriptId":"u40"},
    "ddd86742aa544ee89fa89d8ee862c402":{
      "scriptId":"u41"},
    "85d0752331414f8799886d216cbae6a2":{
      "scriptId":"u42"},
    "2c56e16286194aa59419ae901bfe505c":{
      "scriptId":"u43"}}});